/**
 * 内置 MCP 服务器预置定义
 * 常见的 @modelcontextprotocol 官方服务器
 * @author weibin
 */
import type { McpServer } from '../../shared/types'

const NOW = new Date().toISOString()

export const BUILTIN_MCPS: McpServer[] = [
  {
    id: 'mcp-filesystem',
    name: '文件系统',
    description: '允许 AI 读写本地文件系统，适用于文件操作类任务（需要 claude-code 或 iflow）',
    category: 'filesystem',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-filesystem', '.'],
    compatibleProviders: ['claude-code', 'iflow'],
    fallbackMode: 'disabled',
    isInstalled: false,
    installMethod: 'npm',
    installCommand: 'npm install -g @modelcontextprotocol/server-filesystem',
    source: 'builtin',
    version: 'latest',
    author: 'Anthropic',
    homepage: 'https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem',
    isGlobalEnabled: false,
    tags: ['filesystem', 'files', 'official'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mcp-git',
    name: 'Git 操作',
    description: '提供 Git 仓库操作能力，包括查看历史、分支管理、diff 等（需要 Python 环境，通过 uvx 运行）',
    category: 'code',
    transport: 'stdio',
    command: 'uvx',
    args: ['mcp-server-git', '--repository', '.'],
    compatibleProviders: ['claude-code', 'iflow'],
    fallbackMode: 'disabled',
    isInstalled: false,
    installMethod: 'pip',
    installCommand: 'pip install mcp-server-git',
    source: 'builtin',
    version: 'latest',
    author: 'Anthropic',
    homepage: 'https://github.com/modelcontextprotocol/servers/tree/main/src/git',
    isGlobalEnabled: false,
    tags: ['git', 'vcs', 'official'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mcp-sqlite',
    name: 'SQLite 数据库',
    description: '直接查询和操作 SQLite 数据库文件，适合本地数据分析（需要 Python 环境，通过 uvx 运行）',
    category: 'database',
    transport: 'stdio',
    command: 'uvx',
    args: ['mcp-server-sqlite'],
    compatibleProviders: ['claude-code', 'iflow'],
    fallbackMode: 'disabled',
    configSchema: {
      type: 'object',
      properties: {
        DB_PATH: { type: 'string', description: 'SQLite 数据库文件路径', default: './database.db' },
      },
    },
    isInstalled: false,
    installMethod: 'pip',
    installCommand: 'pip install mcp-server-sqlite',
    source: 'builtin',
    version: 'latest',
    author: 'Anthropic',
    homepage: 'https://github.com/modelcontextprotocol/servers/tree/main/src/sqlite',
    isGlobalEnabled: false,
    tags: ['database', 'sqlite', 'official'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mcp-github',
    name: 'GitHub API',
    description: '访问 GitHub API，包括 Issues、PR、仓库操作、代码搜索等',
    category: 'code',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-github'],
    compatibleProviders: ['claude-code', 'iflow'],
    fallbackMode: 'disabled',
    configSchema: {
      type: 'object',
      properties: {
        GITHUB_PERSONAL_ACCESS_TOKEN: {
          type: 'string',
          description: 'GitHub Personal Access Token（需要 repo 权限）',
        },
      },
      required: ['GITHUB_PERSONAL_ACCESS_TOKEN'],
    },
    envVars: { GITHUB_PERSONAL_ACCESS_TOKEN: '' },
    isInstalled: false,
    installMethod: 'npm',
    installCommand: 'npm install -g @modelcontextprotocol/server-github',
    source: 'builtin',
    version: 'latest',
    author: 'Anthropic',
    homepage: 'https://github.com/modelcontextprotocol/servers/tree/main/src/github',
    isGlobalEnabled: false,
    tags: ['github', 'git', 'api', 'official'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mcp-brave-search',
    name: 'Brave 搜索',
    description: '使用 Brave Search API 进行网络搜索，获取实时网络信息',
    category: 'web',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-brave-search'],
    compatibleProviders: ['claude-code', 'iflow'],
    fallbackMode: 'disabled',
    configSchema: {
      type: 'object',
      properties: {
        BRAVE_API_KEY: { type: 'string', description: 'Brave Search API Key（从 brave.com/search/api 获取）' },
      },
      required: ['BRAVE_API_KEY'],
    },
    envVars: { BRAVE_API_KEY: '' },
    isInstalled: false,
    installMethod: 'npm',
    installCommand: 'npm install -g @modelcontextprotocol/server-brave-search',
    source: 'builtin',
    version: 'latest',
    author: 'Anthropic',
    homepage: 'https://github.com/modelcontextprotocol/servers/tree/main/src/brave-search',
    isGlobalEnabled: false,
    tags: ['search', 'web', 'official'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mcp-postgres',
    name: 'PostgreSQL',
    description: '连接和查询 PostgreSQL 数据库，支持 SQL 查询和 schema 探索',
    category: 'database',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-postgres'],
    compatibleProviders: ['claude-code', 'iflow'],
    fallbackMode: 'disabled',
    configSchema: {
      type: 'object',
      properties: {
        POSTGRES_CONNECTION_STRING: {
          type: 'string',
          description: 'PostgreSQL 连接字符串，格式：postgresql://user:password@localhost:5432/dbname',
        },
      },
      required: ['POSTGRES_CONNECTION_STRING'],
    },
    envVars: { POSTGRES_CONNECTION_STRING: '' },
    isInstalled: false,
    installMethod: 'npm',
    installCommand: 'npm install -g @modelcontextprotocol/server-postgres',
    source: 'builtin',
    version: 'latest',
    author: 'Anthropic',
    homepage: 'https://github.com/modelcontextprotocol/servers/tree/main/src/postgres',
    isGlobalEnabled: false,
    tags: ['database', 'postgresql', 'official'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ===== 浏览器自动化 =====
  {
    id: 'mcp-playwright',
    name: 'Playwright 浏览器自动化',
    description: 'Microsoft 官方 Playwright MCP 服务器，让 AI 通过结构化可访问性树与网页交互',
    category: 'browser',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@executeautomation/playwright-mcp-server'],
    compatibleProviders: ['claude-code', 'iflow'],
    fallbackMode: 'disabled',
    isInstalled: false,
    installMethod: 'npm',
    installCommand: 'npm install -g @executeautomation/playwright-mcp-server',
    source: 'builtin',
    version: 'latest',
    author: 'Microsoft/ExecuteAutomation',
    homepage: 'https://github.com/executeautomation/mcp-playwright',
    isGlobalEnabled: false,
    tags: ['browser', 'automation', 'playwright', 'web'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ===== 容器编排 =====
  {
    id: 'mcp-kubernetes',
    name: 'Kubernetes 集群管理',
    description: 'Kubernetes MCP 服务器，支持 Pod、Deployment、Service 等资源的 CRUD 操作',
    category: 'infrastructure',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', 'mcp-server-kubernetes'],
    compatibleProviders: ['claude-code', 'iflow'],
    fallbackMode: 'disabled',
    isInstalled: false,
    installMethod: 'npm',
    installCommand: 'npm install -g mcp-server-kubernetes',
    source: 'builtin',
    version: 'latest',
    author: 'Flux159',
    homepage: 'https://github.com/Flux159/mcp-server-kubernetes',
    isGlobalEnabled: false,
    tags: ['kubernetes', 'k8s', 'docker', 'infrastructure', 'devops'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ===== 网络请求 =====
  {
    id: 'mcp-fetch',
    name: 'HTTP/Fetch 请求',
    description: '为 AI 提供 HTTP 请求能力，支持 GET/POST/PUT/DELETE 等方法',
    category: 'web',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-fetch'],
    compatibleProviders: ['claude-code', 'iflow'],
    fallbackMode: 'disabled',
    isInstalled: false,
    installMethod: 'npm',
    installCommand: 'npm install -g @modelcontextprotocol/server-fetch',
    source: 'builtin',
    version: 'latest',
    author: 'Anthropic',
    homepage: 'https://github.com/modelcontextprotocol/servers/tree/main/src/fetch',
    isGlobalEnabled: false,
    tags: ['http', 'api', 'fetch', 'web', 'official'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ===== 搜索引擎 =====
  {
    id: 'mcp-google-search',
    name: 'Google 搜索 (SerpAPI)',
    description: '通过 SerpAPI 进行 Google 搜索，获取实时网络信息（需要 SerpAPI Key）',
    category: 'web',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', 'mcp-server-google-search'],
    compatibleProviders: ['claude-code', 'iflow'],
    fallbackMode: 'disabled',
    configSchema: {
      type: 'object',
      properties: {
        SERPAPI_KEY: {
          type: 'string',
          description: 'SerpAPI Key（从 serpapi.com 获取）',
        },
      },
      required: ['SERPAPI_KEY'],
    },
    envVars: { SERPAPI_KEY: '' },
    isInstalled: false,
    installMethod: 'npm',
    installCommand: 'npm install -g mcp-server-google-search',
    source: 'builtin',
    version: 'latest',
    author: 'Community',
    homepage: 'https://github.com/anthropics/anthropic-cookbook',
    isGlobalEnabled: false,
    tags: ['search', 'google', 'web', 'api'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ===== 开发工具 =====
  {
    id: 'mcp-puppeteer',
    name: 'Puppeteer 浏览器控制',
    description: '使用 Puppeteer 进行浏览器自动化，支持网页导航、截图、PDF 生成等',
    category: 'browser',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-puppeteer'],
    compatibleProviders: ['claude-code', 'iflow'],
    fallbackMode: 'disabled',
    isInstalled: false,
    installMethod: 'npm',
    installCommand: 'npm install -g @modelcontextprotocol/server-puppeteer',
    source: 'builtin',
    version: 'latest',
    author: 'Anthropic',
    homepage: 'https://github.com/modelcontextprotocol/servers/tree/main/src/puppeteer',
    isGlobalEnabled: false,
    tags: ['browser', 'puppeteer', 'automation', 'official'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ===== 云服务 =====
  {
    id: 'mcp-aws',
    name: 'AWS 云服务',
    description: 'AWS 官方 MCP 服务器，无缝集成 AWS 服务和资源',
    category: 'cloud',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@awslabs/mcp'],
    compatibleProviders: ['claude-code', 'iflow'],
    fallbackMode: 'disabled',
    isInstalled: false,
    installMethod: 'npm',
    installCommand: 'npm install -g @awslabs/mcp',
    source: 'builtin',
    version: 'latest',
    author: 'AWS Labs',
    homepage: 'https://github.com/awslabs/mcp',
    isGlobalEnabled: false,
    tags: ['aws', 'cloud', 'amazon', 'official'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ===== AI/ML 工具 =====
  {
    id: 'mcp-ollama',
    name: 'Ollama 本地 LLM',
    description: '连接本地 Ollama 实例，管理本地大语言模型',
    category: 'ai',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', 'mcp-server-ollama'],
    compatibleProviders: ['claude-code', 'iflow'],
    fallbackMode: 'disabled',
    configSchema: {
      type: 'object',
      properties: {
        OLLAMA_HOST: {
          type: 'string',
          description: 'Ollama 服务地址',
          default: 'http://localhost:11434',
        },
      },
    },
    envVars: { OLLAMA_HOST: 'http://localhost:11434' },
    isInstalled: false,
    installMethod: 'npm',
    installCommand: 'npm install -g mcp-server-ollama',
    source: 'builtin',
    version: 'latest',
    author: 'Community',
    homepage: 'https://github.com/ollama/ollama',
    isGlobalEnabled: false,
    tags: ['ai', 'llm', 'ollama', 'local'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ===== 文档处理 =====
  {
    id: 'mcp-memory',
    name: '知识图谱内存',
    description: '基于知识图谱的持久化内存系统，让 AI 记住跨会话的信息',
    category: 'memory',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-memory'],
    compatibleProviders: ['claude-code', 'iflow'],
    fallbackMode: 'disabled',
    isInstalled: false,
    installMethod: 'npm',
    installCommand: 'npm install -g @modelcontextprotocol/server-memory',
    source: 'builtin',
    version: 'latest',
    author: 'Anthropic',
    homepage: 'https://github.com/modelcontextprotocol/servers/tree/main/src/memory',
    isGlobalEnabled: false,
    tags: ['memory', 'knowledge', 'persistent', 'official'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ===== 时间/调度 =====
  {
    id: 'mcp-sequential-thinking',
    name: '顺序思考工具',
    description: '通过思维链方式进行动态、反思性的问题解决',
    category: 'thinking',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-sequential-thinking'],
    compatibleProviders: ['claude-code', 'iflow'],
    fallbackMode: 'disabled',
    isInstalled: false,
    installMethod: 'npm',
    installCommand: 'npm install -g @modelcontextprotocol/server-sequential-thinking',
    source: 'builtin',
    version: 'latest',
    author: 'Anthropic',
    homepage: 'https://github.com/modelcontextprotocol/servers/tree/main/src/sequentialthinking',
    isGlobalEnabled: false,
    tags: ['thinking', 'reasoning', 'chain-of-thought', 'official'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ===== 代码分析 =====
  {
    id: 'mcp-sentry',
    name: 'Sentry 错误追踪',
    description: '集成 Sentry 错误追踪服务，检索和分析应用错误',
    category: 'monitoring',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-sentry'],
    compatibleProviders: ['claude-code', 'iflow'],
    fallbackMode: 'disabled',
    configSchema: {
      type: 'object',
      properties: {
        SENTRY_AUTH_TOKEN: {
          type: 'string',
          description: 'Sentry Auth Token',
        },
      },
      required: ['SENTRY_AUTH_TOKEN'],
    },
    envVars: { SENTRY_AUTH_TOKEN: '' },
    isInstalled: false,
    installMethod: 'npm',
    installCommand: 'npm install -g @modelcontextprotocol/server-sentry',
    source: 'builtin',
    version: 'latest',
    author: 'Anthropic',
    homepage: 'https://github.com/modelcontextprotocol/servers/tree/main/src/sentry',
    isGlobalEnabled: false,
    tags: ['monitoring', 'error-tracking', 'sentry', 'official'],
    createdAt: NOW,
    updatedAt: NOW,
  },
]
